name: 0 Deploy PoC Enviroment
on: workflow_dispatch

env:
  AZURE_RG: OABoT_POC
  AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  AZURE_REGION: eastus
 
jobs:
  deploy-bicep-template:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
    - uses: actions/checkout@main
      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}
